# Arrays in Python
## Lists
Lists are the most general array in python. Lists can contain a mix of any data type. You can often get away with using mathematical operations on numbers in mixed arrays

In [ ]:
l = [9, 'monkey', 2+3j]
print(l[1])
l[0]*l[0]

Note that indexing starts at 0 **(unlike in MATLAB)**. Some useful functions with lists in Python

In [19]:
l.append('addon')
print(l)
l.pop(1)
l.remove(9)
print(l)

[9, 'monkey', (2+3j), 'addon']
[(2+3j), 'addon']


## Arrays
Arrays in Python are:
1. fixed in size
1. all elements must be of the same type
1. multi-dimensional

The *array* command is stored in the package _numpy_. Arrays can always be used in arithmetic operations, and they store data more efficiently than lists, so when storing lots of data, use arrays.

In [23]:
from numpy import array
a = array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


![python indexing](figures/pythonarray.png)

You can slice lists and arrays with a colon **:**

- a[m:n] = subset of *a* starting at index *m* up to but not including *n*
- a[m:n,p:q] = subset of a 2-D array *a* starting in row *m* and column *p* up to but not including row *n* and column *q* 
- a[m:n:step,p:q:step]  = subset of array *a* choosing an element at each step

Omitting numbers before colon means start at the beginning and after the colon means go to end

In [26]:
a[0:3]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
a[1:3,3]

array([19, 24])

In [30]:
a[::2,::2]

array([[11, 13, 15],
       [21, 23, 25],
       [31, 33, 35]])

## Useful Functions
Some functions in *numpy* help creating and importing arrays. You may also turn lists into arrays.

In [10]:
import numpy as np
A=np.zeros([3,3],int)
B=np.ones([3,3],float)
print(A)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
list1 = [3,5,1,3,5,6]
print(list1)

[3, 5, 1, 3, 5, 6]


In [13]:
np.array(list1,float)

array([3., 5., 1., 3., 5., 6.])

Wait a minute! Are you saying I can only get 1D arrays from lists? Well, no. Let's use **lists of lists**

In [16]:
list2 = [[1,4,3],[3,4,9],[-1,4,2]]
list2[1][2]

9

In [21]:
newarray = np.array(list2,float)
print(newarray)

[[ 1.  4.  3.]
 [ 3.  4.  9.]
 [-1.  4.  2.]]


You can load data from files **fairly** easily with *loadtxt*. Documentation on *dtype* and the notation used below is available at https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dtype.html

In [62]:
test=np.loadtxt("data/HeatCapCoef.txt", dtype={'names': ('gas','HC', 'error1', 'error2','error3'),
...                      'formats': ('S5', 'f4', 'f4','f4','f4')})

In [67]:
id = test['HC']>29
tp=test['error1'][id]
print(tp)

[-0.00192  0.00192]


In [65]:
test['HC']

array([28.883, 25.46 , 29.088, 28.142, 22.243, 32.218, 24.619, 19.875],
      dtype=float32)